### ISSUE TITLE
더 알아보기 버튼 hover 인식 영역 문제

### ISSUE THREAD

**Issue by BasixKOR** [Team-NiNE/team-nine.github.io#3]
1. `>`에 닿지 않고 흰색 부분에만 닿는 경우 버튼이 펼쳐지지 않음.
2. 펼쳐진 상태의 버튼이 있을 오른쪽 부분에 마우스를 가져다 되면 버튼이 펼쳐짐.

## 자료용 GIF
![1](https://user-images.githubusercontent.com/7413880/40317083-4e08a782-5d5b-11e8-89ed-6d3d674a860d.png)
1번에 대한 참고자료
![2](https://user-images.githubusercontent.com/7413880/40317101-5c26c39e-5d5b-11e8-82ed-fdb3169f81fd.gif)
2번에 대한 참고자료

**Comment by hakasenyang** [comment]
1. 메뉴 부분으로 인해 겹쳐져 있어 hover 인식이 되지 않은 문제로 파악됩니다.
현재 수정중이에요.
여기서 메뉴는 about us 있는 부분의 영역을 말해요.
2. 이 부분 문제는 파악 중입니다.


1번에 대한 참고자료
![image](https://user-images.githubusercontent.com/16399606/40319778-49762376-5d64-11e8-821a-c5b945dcdc2a.png)

**Comment by hakasenyang** [comment]
2번 문제는 텍스트의 width 가 0 임에도 불구하고 자리를 차지하는 것으로 보입니다.
따라서, 해당 문제는 visibility(css) 를 통해 해결하였습니다.

**Comment by hakasenyang** [comment]
![2018-05-22_02-46-28](https://user-images.githubusercontent.com/16399606/40321529-5caeb42a-5d6a-11e8-97cb-2318f1986aa5.gif)
문제에 대한 해결 이미지입니다.

**Comment by Hoto-Cocoa** [comment]
Closed by #4.
